name: Test Project
on: push
jobs:
  VerifyTest:
   runs-on: ubuntu-latest
   steps:
    - name: Download Code
      uses: actions/checkout@v3
    - name: Install Node 
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: install npm
      run : npm ci 
    - name: Execute Test script 
      run: npm run test
  deploy:
   need: VerifyTest
   runs-on: ubuntu-latest
   steps:
    - name: Download Code 
      uses: actions/checkout@v3
    - name: Install Node Js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: install npm 
      run:  npm ci
    - name: Build Project
      run: npm run build
    - name: Deploy
      run: echo "Deployment Complete"      

